sudo: required # super user required
services:
  - docker #tells travis that we need docker

# build out docker image before it runs
# We will first run our dev version so we can test
before_install:
  - docker build -i cmcaboy/docker-react -f Dockerfile.dev .

# contains the commands to run our test suite
# IF any command returns a non-zero value, travis
# will stop execution
# -- --coverage will execute npm run test just once in non-interactive mode
script:
  - docker run cmcaboy/docker-react npm run test -- --coverage
