version: "3"
services:
  web:
    build:
      context: . # project directory
      dockerfile: Dockerfile.dev # name of docker file
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
